// Generated by CoffeeScript 1.7.1
(function() {
  var frontControl;

  frontControl = module.exports = {
    landing: function(req, res) {
      res.render("homeContent");
      return false;
    }
  };

}).call(this);
