// Generated by CoffeeScript 1.6.3
(function() {
  var exec, frontControl;

  exec = (require("child_process")).exec;

  frontControl = module.exports = {
    landing: function(req, res) {
      res.render("landing");
      return false;
    },
    getImageUrl: function(req, res) {
      return function() {
        var data;
        data = exec("phantomjs test.js", function(error, stdout, stderr) {
          return stdout;
        });
        console.log(data);
        return data;
      };
    }
  };

}).call(this);
