// Generated by CoffeeScript 1.7.1
(function() {
  var binPath, childProcess, path, phantomjs;

  path = require("path");

  childProcess = require("child_process");

  phantomjs = require("phantomjs");

  binPath = phantomjs.path;

  module.exports = {
    getDataUrl: function(req, res) {
      var childArgs;
      console.log("route triggered");
      childArgs = [path.join(__dirname, "test.js"), "test argument"];
      childProcess.execFile(binPath, childArgs, function(err, stdout, stderr) {
        console.log("print in control", stdout);
        res.send(stdout);
        return false;
      });
      return false;
    }
  };

}).call(this);
